language: swift
os: osx
osx_image: xcode10
xcode_workspace: FSNotes.xcworkspace

env:
    - SCHEME=FSNotes SDK=macosx
    - SCHEME="FSNotes iOS" SDK=iphonesimulator

script: xcodebuild -workspace FSNotes.xcworkspace -scheme "$SCHEME" build -sdk $SDK ONLY_ACTIVE_ARCH=NO

branches:
    only: [master]
